# Generated by Django 5.0 on 2024-12-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_script_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
